import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { z } from "zod";

import { env } from "@/lib/env";
import { auth } from "@/lib/auth";
import { asApiError, AppError } from "@/lib/errors";

const generateSchema = z.object({
  channel: z.enum(["EMAIL", "SMS", "WHATSAPP", "PUSH"]),
  segmentName: z.string().trim().optional(),
  instructions: z.string().trim().min(3).max(500)
});

const client = new GoogleGenerativeAI(env.GEMINI_API_KEY);

function buildPrompt(channel: string, instructions: string, segmentName?: string) {
  return `You are a highly converting marketing copywriter. 
Write a marketing message tailored for the channel: ${channel}.
${segmentName ? `Target Audience: "${segmentName}"` : ""}
Copywriting Directions: "${instructions}"

Formatting Rules:
- EMAIL: Start with "Subject: <Subject Line>" on the first line, then leave a blank line, and write the email body.
- SMS: Must be text-only, highly punchy, under 160 characters, with a clear CTA.
- WHATSAPP: Short, engaging copy. Use formatting if helpful (*bold*, _italics_) and emojis, with a clear CTA.
- PUSH (RCS): Teaser message format, text only, under 120 characters.

Do not output any markdown code blocks (like \`\`\` or \`\`\`html), preamble, explanations, or quotes. Output ONLY the raw final copy.`;
}

export async function POST(request: Request) {
  try {
    const session = await auth();
    if (!session?.user) {
      throw new AppError("Unauthorized", 401);
    }

    const body = await request.json();
    const parsed = generateSchema.safeParse(body);

    if (!parsed.success) {
      throw new AppError("Enter valid generation instructions.", 400);
    }

    const { channel, segmentName, instructions } = parsed.data;

    const model = client.getGenerativeModel({ model: "gemini-1.5-flash" });
    const prompt = buildPrompt(channel, instructions, segmentName);

    let text = "";
    try {
      const result = await model.generateContent(prompt);
      text = result.response.text().trim();
      // Clean up any markdown code block wrap if generated by AI
      text = text.replace(/^```[a-z]*\n?/i, "").replace(/\n?```$/, "").trim();
    } catch (err) {
      // Fallback message templates if Gemini API fails (e.g. invalid key)
      const fallbackTemplates: Record<string, string> = {
        EMAIL: `Subject: Exclusive offer for you! 🎁\n\nDear customer,\n\nWe have a special promotion tailored just for you based on your preferences: "${instructions}".\nUse coupon code GROW20 to claim 20% off at checkout.\n\nBest regards,\nMarketing Team`,
        SMS: `Promo: ${instructions.slice(0, 80)}! Use code SHINE10 for 10% off. Stop to optout.`,
        WHATSAPP: `Hey there! 👋\n\n*Special Campaign for you:* ${instructions}\n\nEnjoy free shipping and instant cashback this weekend. Use code *WP50* at checkout!\n\nBuy now: bit.ly/shop-now`,
        PUSH: `Alert: ${instructions.slice(0, 60)}! Click to learn more.`
      };
      text = fallbackTemplates[channel] || `Special campaign: ${instructions}`;
    }

    return NextResponse.json({ copy: text });
  } catch (error) {
    const apiError = asApiError(error);
    return NextResponse.json({ message: apiError.message }, { status: apiError.statusCode });
  }
}
