import { GoogleGenerativeAI } from "@google/generative-ai";

import { env } from "@/lib/env";
import { buildAudiencePrompt } from "@/lib/audience/prompt";
import { buildFallbackRule } from "@/lib/audience/fallback";
import { segmentRuleSchema } from "@/lib/audience/types";

const client = new GoogleGenerativeAI(env.GEMINI_API_KEY);

function extractJson(text: string) {
  const trimmed = text.trim();
  const fenced = trimmed.match(/```json\s*([\s\S]*?)```/i);
  if (fenced?.[1]) return fenced[1].trim();
  return trimmed;
}

export async function generateAudienceRule(prompt: string) {
  const model = client.getGenerativeModel({ model: "gemini-1.5-flash" });

  try {
    const result = await model.generateContent(buildAudiencePrompt(prompt));
    const text = result.response.text();
    const parsed = JSON.parse(extractJson(text));
    const rule = segmentRuleSchema.parse(parsed);

    return {
      rule,
      explanation: "AI generated a structured audience rule.",
      source: "ai" as const
    };
  } catch {
    const fallback = buildFallbackRule(prompt);

    if (!fallback.rule) {
      return {
        rule: null,
        explanation: fallback.explanation,
        source: "fallback" as const
      };
    }

    return {
      rule: fallback.rule,
      explanation: `${fallback.explanation}. This was generated by fallback recovery because the AI response could not be parsed safely.`,
      source: "fallback" as const
    };
  }
}
